spring.application.name=library-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://library-db:5432/${LIBRARY_DB_NAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# SpringDoc Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.server.url=${GATEWAY_URL:http://localhost:8080}/api/library
springdoc.swagger-ui.server.description=API Gateway

# JWT Configuration
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=when-authorized
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
