apiVersion: v1
kind: Secret
metadata:
  name: library-service-secret
  namespace: library-app
  labels:
    app: library-service
type: Opaque
stringData:
  # Database Configuration
  # WICHTIG: Diese Werte müssen vor dem Deployment angepasst werden!
  database-url: "jdbc:postgresql://library-postgres-service:5432/library_db"
  database-username: "postgres"
  database-password: "postgres"
  
  # JWT Secret Key
  jwt-secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"