apiVersion: v1
kind: Service
metadata:
  name: library-service
  namespace: library-app
  labels:
    app: library-service
spec:
  selector:
    app: library-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP