apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-postgres
  namespace: library-app
spec:
  serviceName: "auth-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
      - name: auth-postgres
        image: postgres:15-alpine
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"  # 100m = 0.1 CPU Kern
          limits:
            memory: "512Mi"
            cpu: "500m" # 500m = 0.5 CPU Kern
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: auth-postgres-configmap
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: auth-postgres-configmap
              key: POSTGRES_DB
        volumeMounts:
        - name: auth-postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: auth-postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi